"""
Self-contained carwash-type classifier for our own sites in main-ds.csv.

Single file. No dependency on the type_car_wash package -- the website
finder, the Jina scraper, and the Azure OpenAI classifier are all inlined
below so this script can be copied/run anywhere with just:

    pip install pandas requests beautifulsoup4 openai python-dotenv

Pipeline, per unique site (client_id + site_id):
    0. lookup from carwash_list_clean.csv     -> URL          (instant, free, no API)
    1. find_website_google_places(name, ...)  -> URL          (Google Places API)
    2. find_official_website(name, address)   -> URL          (DuckDuckGo)
    3. scrape_site(url)                       -> text         (Jina Reader)
    4. classify(text)                         -> primary_type (Azure OpenAI)

The scrape+classify step is website-level (brand websites are shared across
locations), so it is CACHED BY RESOLVED URL: two sites of the same brand that
resolve to the same site share one classification and therefore get the same
type -- a limitation of the data source, not a bug. Output is still one row
PER SITE, so granularity is client_id + site_id.

Resume: re-running skips (client_id, site_id) pairs already in the output.

Env (.env at repo root): AZURE_OPENAI_API_KEY required, JINA_API_KEY optional.

Usage:
    python earnest-proforma-2.0/classify_site_types.py --limit 8   # test batch
    python earnest-proforma-2.0/classify_site_types.py             # full run
"""

import argparse
import csv
import json
import os
import re
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Optional
from urllib.parse import urljoin, urlparse, unquote

import pandas as pd
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from openai import AzureOpenAI

# --------------------------------------------------------------------------
# CONFIG
# --------------------------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
load_dotenv(os.path.join(REPO_ROOT, ".env"))

JINA_API_KEY = os.getenv("JINA_API_KEY")
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
# Azure OpenAI resource (eastus2). Endpoint comes from AZURE_OPENAI_ENDPOINT in
# .env, defaulting to the proforma resource. DEPLOYMENT is the Azure deployment
# name (passed as the `model` arg), backed by gpt-4o-2024-11-20.
AZURE_ENDPOINT = os.getenv(
    "AZURE_OPENAI_ENDPOINT",
    "https://soneastus2proformaai.openai.azure.com/"
)
AZURE_API_VERSION = "2024-02-15-preview"
DEPLOYMENT = "gpt-4o"

DEFAULT_INPUT = os.path.join(HERE, "data", "main-ds.csv")
DEFAULT_OUTPUT = os.path.join(HERE, "data", "site_carwash_types.csv")

VALID_TYPES = [
    "Express Tunnel", "Full Service", "In-Bay Automatic", "Self-Serve",
    "Touchless", "Hand Wash / Detail", "Flex", "Mobile", "Unknown",
]

OUTPUT_FIELDS = [
    "client_id", "site_id", "client_name", "website", "website_confidence",
    "primary_carwash_type", "classify_confidence", "secondary_types", "reasoning",
]

HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                         "(KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"}
BLOCKED_DOMAINS = ["yelp.com", "facebook.com", "instagram.com", "linkedin.com",
                   "mapquest.com", "tripadvisor.com", "yellowpages.com", "bbb.org",
                   # auto-generated business-listing microsites with no service content
                   "edan.io", "business.site", "g.page", "goo.gl", "sites.google.com",
                   "godaddysites.com", "negocio.site"]

# Path to the pre-built competitor name→website lookup table.
# Generated by flatten_carwash_list.py + clean_carwash_list.py.
# Override at runtime via the --lookup CLI argument.
LOOKUP_CSV = os.path.join(HERE, "carwash_list_clean.csv")
LOOKUP_FUZZY_THRESHOLD = 85   # rapidfuzz score (0-100); tune if needed


# --------------------------------------------------------------------------
# 0. WEBSITE LOOKUP from pre-built competitor list (carwash_list_clean.csv)
# --------------------------------------------------------------------------
_lookup_table: dict = {}   # normalised_name -> best_url
_lookup_loaded = False
_lookup_lock = threading.Lock()


def _normalize_name(s: str) -> str:
    """Lowercase and strip common car-wash suffixes for better fuzzy matching."""
    s = s.lower().strip()
    # Remove trailing noise words so 'Big Dan's' matches 'Big Dan's Car Wash'
    for suffix in [
        " car wash", " carwash", " auto wash", " auto spa",
        " express car wash", " express wash", " express",
        " car care", " & lube", " and lube", " detail center",
    ]:
        if s.endswith(suffix):
            s = s[: -len(suffix)].strip()
    return s


def _load_lookup():
    """Load carwash_list_clean.csv into _lookup_table (called once, thread-safe)."""
    global _lookup_table, _lookup_loaded
    with _lookup_lock:
        if _lookup_loaded:
            return
        if not os.path.exists(LOOKUP_CSV):
            print(f"[lookup] WARNING: {LOOKUP_CSV} not found – skipping lookup step")
            _lookup_loaded = True
            return
        from collections import Counter
        df = pd.read_csv(LOOKUP_CSV, dtype=str)
        name_to_urls: dict = {}
        for _, row in df.iterrows():
            name = str(row.get("Carwash Name") or "").strip()
            url  = str(row.get("Carwash Website") or "").strip()
            if not name or not url:
                continue
            key = _normalize_name(name)
            name_to_urls.setdefault(key, []).append(url)
        # For each normalised name, keep the most-common URL
        for key, urls in name_to_urls.items():
            _lookup_table[key] = Counter(urls).most_common(1)[0][0]
        _lookup_loaded = True
        print(f"[lookup] Loaded {len(_lookup_table)} unique entries from {LOOKUP_CSV}")


def find_website_from_lookup(name: str):
    """
    Returns (url, confidence) by matching `name` against carwash_list_clean.csv.

    Strategy:
      1. Exact normalised match        → confidence 95
      2. rapidfuzz token_sort_ratio    → confidence = score (if >= LOOKUP_FUZZY_THRESHOLD)
      3. No match                      → (None, 0)

    rapidfuzz is optional; if not installed the fuzzy step is silently skipped.
    Install with:  pip install rapidfuzz
    """
    _load_lookup()
    if not _lookup_table:
        return None, 0

    norm = _normalize_name(name)

    # 1. Exact normalised match
    if norm in _lookup_table:
        return _lookup_table[norm], 95

    # 2. Fuzzy match via rapidfuzz
    try:
        from rapidfuzz import process as rfprocess, fuzz as rffuzz
        result = rfprocess.extractOne(
            norm,
            _lookup_table.keys(),
            scorer=rffuzz.token_sort_ratio,
            score_cutoff=LOOKUP_FUZZY_THRESHOLD,
        )
        if result:
            matched_key, score, _ = result
            return _lookup_table[matched_key], int(score)
    except ImportError:
        pass   # rapidfuzz not installed; skip fuzzy step silently

    return None, 0


# --------------------------------------------------------------------------
# 1. WEBSITE FINDER (DuckDuckGo)
# --------------------------------------------------------------------------
def _clean(text: str) -> str:
    text = re.sub(r"[^a-z0-9 ]", " ", text.lower())
    return re.sub(r"\s+", " ", text).strip()


def _real_url(ddg_url: str) -> str:
    parsed = urlparse(ddg_url)
    if "duckduckgo.com" in parsed.netloc:
        m = re.search(r"uddg=(.*?)&", parsed.query)
        if m:
            return unquote(m.group(1))
    return ddg_url


def _blocked(url: str) -> bool:
    d = urlparse(url).netloc.lower()
    return any(b in d for b in BLOCKED_DOMAINS)


def _domain_score(url: str, name: str) -> int:
    domain = urlparse(url).netloc.lower()
    score = sum(15 for w in _clean(name).split() if len(w) > 2 and w in domain)
    return min(score, 50)


def _content_score(url: str, name: str, address: Optional[str]) -> int:
    try:
        text = _clean(requests.get(url, headers=HEADERS, timeout=8).text)
    except Exception:
        return 0
    score = sum(10 for w in _clean(name).split() if len(w) > 2 and w in text)
    if "car wash" in text or "auto wash" in text:
        score += 10
    if address:
        for w in _clean(address).split():
            if len(w) > 3 and w in text:
                score += 5
                break
    return min(score, 50)


def _search_ddg(query: str) -> list:
    try:
        resp = requests.post("https://html.duckduckgo.com/html/",
                             data={"q": query}, headers=HEADERS, timeout=15)
    except Exception:
        return []
    soup = BeautifulSoup(resp.text, "html.parser")
    out = []
    for a in soup.find_all("a", class_="result__a", href=True):
        u = _real_url(a["href"])
        if u and u.startswith("http"):
            out.append(u)
    return out


def find_official_website(name: str, address: Optional[str] = None):
    """Returns (url, confidence 0-100); url is None if below threshold."""
    locality = ""
    if address and "," in address:
        locality = ", ".join(address.split(",")[1:]).strip()
    query = f"{name} {locality} car wash official website".strip() if locality \
        else f"{name} car wash official website"
    results = _search_ddg(query)
    if not results:
        return None, 0
    best, best_score = None, 0
    for link in results[:8]:
        if _blocked(link):
            continue
        total = _domain_score(link, name) + _content_score(link, name, address)
        if total > best_score:
            best, best_score = link, total
        time.sleep(1)
    if best_score >= 30:
        return best, best_score
    return None, best_score


# --------------------------------------------------------------------------
# 1b. WEBSITE FINDER via Google Places API v1 (more accurate, per-location)
# --------------------------------------------------------------------------
def find_website_google_places(name, address, lat=None, lon=None):
    """
    Look up the specific physical location on Google Places (Text Search New)
    and return its official websiteUri. Biased to the site's lat/lon so the
    correct location of a multi-site brand is picked. Returns (url, conf) where
    conf is 90 for a Places hit, or (None, 0) if nothing usable.
    """
    if not GOOGLE_MAPS_API_KEY:
        return None, 0
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": GOOGLE_MAPS_API_KEY,
        "X-Goog-FieldMask": "places.id,places.displayName,places.websiteUri,places.formattedAddress",
    }
    payload = {
        "textQuery": f"{name} {address}".strip(),
        "includedType": "car_wash",
        "maxResultCount": 1,
    }
    try:
        if lat is not None and lon is not None and not (pd.isna(lat) or pd.isna(lon)):
            payload["locationBias"] = {"circle": {
                "center": {"latitude": float(lat), "longitude": float(lon)},
                "radius": 5000.0}}
    except (TypeError, ValueError):
        pass
    try:
        r = requests.post("https://places.googleapis.com/v1/places:searchText",
                          headers=headers, data=json.dumps(payload), timeout=15)
        r.raise_for_status()
        places = r.json().get("places", [])
    except Exception:
        return None, 0
    if not places:
        return None, 0
    url = places[0].get("websiteUri")
    if not url or _blocked(url):
        return None, 0
    return url, 90


# --------------------------------------------------------------------------
# 2. SCRAPER (Jina Reader)
# --------------------------------------------------------------------------
def _scrape_jina(url: str) -> str:
    headers = {"Authorization": f"Bearer {JINA_API_KEY}"} if JINA_API_KEY else {}
    try:
        r = requests.get(f"https://r.jina.ai/{url}", headers=headers, timeout=40)
        r.raise_for_status()
        return r.text
    except Exception:
        return ""


def _internal_links(base_url: str, md: str) -> set:
    base_domain = urlparse(base_url).netloc
    keywords = ["service", "wash", "price", "pricing", "package", "detail", "menu"]
    links = set()
    for link in re.findall(r"\[.*?\]\((.*?)\)", md):
        if link.startswith("#") or link.startswith("javascript:"):
            continue
        full = urljoin(base_url, link)
        p = urlparse(full)
        if p.netloc != base_domain:
            continue
        path = p.path.lower()
        if any(path.endswith(ext) for ext in (".png", ".jpg", ".jpeg", ".gif", ".pdf", ".mp4", ".svg", ".webp")):
            continue
        if any(kw in path for kw in keywords):
            links.add(f"{p.scheme}://{p.netloc}{p.path}")
    return links


def scrape_site(start_url: str, max_pages: int = 3) -> str:
    home = _scrape_jina(start_url)
    if not home:
        return ""
    parts = [f"--- Homepage ({start_url}) ---\n{home}"]
    for link in list(_internal_links(start_url, home))[: max_pages - 1]:
        sub = _scrape_jina(link)
        if sub:
            parts.append(f"\n--- Subpage ({link}) ---\n{sub}")
    return "\n\n".join(parts)


# --------------------------------------------------------------------------
# 3. CLASSIFIER (Azure OpenAI, gpt-4o-mini)
# --------------------------------------------------------------------------
_PROMPT = """You are a world-class car wash classification AI used in a production data pipeline.
Analyze the following scraped website text and classify the car wash into one of:
Express Tunnel (conveyor/tunnel/express/unlimited membership/stay in vehicle),
Full Service (interior cleaning/vacuum included/hand dry/staff cleaning),
In-Bay Automatic (pull into bay/automatic wash bay/rollover),
Self-Serve (coin operated/wash bays/manual spray wand),
Touchless (no brushes/brushless), Hand Wash / Detail (hand wash/detailing/ceramic),
Flex (express exterior + full service option), Mobile (we come to you), or Unknown.

Return valid JSON with fields: primary_type, secondary_types (list),
confidence_score (0..1), found_packages (list), detected_markers (list), reasoning.

SCRAPED TEXT:
{text}
"""

_client = None


def _openai():
    global _client
    if _client is None:
        _client = AzureOpenAI(
            azure_endpoint=AZURE_ENDPOINT,
            api_key=AZURE_OPENAI_API_KEY,
            api_version=AZURE_API_VERSION,
        )
    return _client


def classify(text: str) -> dict:
    if not text:
        return {"primary_type": "Unknown", "confidence_score": 0.0,
                "secondary_types": [], "reasoning": "empty scrape"}
    try:
        comp = _openai().chat.completions.create(
            model=DEPLOYMENT,
            response_format={"type": "json_object"},
            messages=[{"role": "user", "content": _PROMPT.format(text=text[:100000])}],
        )
        data = json.loads(comp.choices[0].message.content or "{}")
        pt = data.get("primary_type", "Unknown")
        return {
            "primary_type": pt if pt in VALID_TYPES else "Unknown",
            "confidence_score": float(data.get("confidence_score", 0.0)),
            "secondary_types": data.get("secondary_types", []),
            "reasoning": data.get("reasoning", ""),
        }
    except Exception as e:
        return {"primary_type": "Unknown", "confidence_score": 0.0,
                "secondary_types": [], "reasoning": f"classify error: {e}"}


# --------------------------------------------------------------------------
# ORCHESTRATION over main-ds.csv
# --------------------------------------------------------------------------
_url_cache, _cls_cache = {}, {}
_url_lock, _cls_lock = threading.Lock(), threading.Lock()


def _address(rec) -> str:
    a = str(rec.get("address1") or "").strip()
    tail = " ".join(x for x in [str(rec.get("state") or "").strip(),
                                str(rec.get("postal_code") or "").strip()]
                    if x and x != "nan")
    return (f"{a}, {tail}".strip().rstrip(",")) if a and a != "nan" else tail


def _resolve(name, address, lat=None, lon=None):
    key = (name.lower(), (address or "").lower())
    with _url_lock:
        if key in _url_cache:
            return _url_cache[key]

    # Step 0: pre-built lookup from merged_all_sites competitor data (instant, free)
    val = find_website_from_lookup(name)
    if val[0]:
        source = "lookup"
    else:
        # Step 1: Google Places API (per-location, most accurate)
        val = find_website_google_places(name, address, lat, lon)
        source = "google_places" if val[0] else None

    if not val[0]:
        # Step 2: DuckDuckGo web search (broad fallback)
        val = find_official_website(name, address)
        source = "duckduckgo" if val[0] else "none"

    if val[0]:
        print(f"[resolve] {name[:40]:40s}  source={source}  url={val[0]}")

    with _url_lock:
        _url_cache[key] = val
    return val


def _classify_url(url):
    with _cls_lock:
        if url in _cls_cache:
            return _cls_cache[url]
    out = classify(scrape_site(url))
    with _cls_lock:
        _cls_cache[url] = out
    return out


def process_site(rec) -> dict:
    name = str(rec["client_name"]).strip()
    row = {"client_id": rec["client_id"], "site_id": rec["site_id"],
           "client_name": name, "website": "", "website_confidence": 0,
           "primary_carwash_type": "Unknown", "classify_confidence": 0.0,
           "secondary_types": "", "reasoning": ""}
    try:
        url, conf = _resolve(name, _address(rec), rec.get("lat"), rec.get("lon"))
        row["website_confidence"] = conf
        if not url:
            row["reasoning"] = "no confident website found"
            return row
        row["website"] = url
        c = _classify_url(url)
        row["primary_carwash_type"] = c["primary_type"]
        row["classify_confidence"] = c["confidence_score"]
        row["secondary_types"] = ";".join(c.get("secondary_types") or [])
        row["reasoning"] = c.get("reasoning", "")
    except Exception as e:
        row["reasoning"] = f"error: {e}"
    return row


def _load_done(path) -> set:
    if not os.path.exists(path):
        return set()
    prev = pd.read_csv(path, dtype=str)
    return {(r["client_id"], str(r["site_id"])) for _, r in prev.iterrows()}


def main():
    global LOOKUP_CSV
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default=DEFAULT_INPUT)
    ap.add_argument("--output", default=DEFAULT_OUTPUT)
    ap.add_argument("--lookup", default=LOOKUP_CSV,
                    help="Path to carwash_list_clean.csv for Step-0 website lookup "
                         "(default: %(default)s)")
    ap.add_argument("--limit", type=int, default=0, help="process only N sites (test)")
    ap.add_argument("--workers", type=int, default=6)
    args = ap.parse_args()

    # Allow overriding the lookup CSV path from the CLI
    LOOKUP_CSV = args.lookup

    if not AZURE_OPENAI_API_KEY:
        raise SystemExit("AZURE_OPENAI_API_KEY not set (check repo-root .env)")

    df = pd.read_csv(args.input, low_memory=False)
    sites = (df.dropna(subset=["client_name"])
             .drop_duplicates(subset=["client_id", "site_id"])
             [["client_id", "site_id", "client_name", "address1", "state", "postal_code", "lat", "lon"]]
             .to_dict("records"))

    done = _load_done(args.output)
    todo = [s for s in sites if (str(s["client_id"]), str(s["site_id"])) not in done]
    if args.limit:
        todo = todo[: args.limit]
    print(f"[*] {len(sites)} sites | {len(done)} done | {len(todo)} to process")

    new_file = not os.path.exists(args.output)
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "a", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=OUTPUT_FIELDS)
        if new_file:
            w.writeheader()
        with ThreadPoolExecutor(max_workers=args.workers) as ex:
            futures = [ex.submit(process_site, s) for s in todo]
            for i, fut in enumerate(as_completed(futures), 1):
                row = fut.result()
                w.writerow(row)
                fh.flush()
                print(f"[{i}/{len(todo)}] {row['client_name'][:38]:38s} -> "
                      f"{row['primary_carwash_type']} ({row['website'] or 'no site'})")

    print(f"\n[done] {args.output} | distinct websites classified: {len(_cls_cache)}")


if __name__ == "__main__":
    main()
