# feature_config.py - 50 features (same set as Approach 2 & 3)

FEATURE_DIRECTION = {
    # Higher is better
    "total_sunshine_hours": "higher",
    "days_pleasant_temp": "higher",
    "Nearest StreetLight US Hourly-Ttl AADT": "higher",
    "2nd Nearest StreetLight US Hourly-Ttl AADT": "higher",
    "3rd Nearest StreetLight US Hourly-Ttl AADT": "higher",
    "4th Nearest StreetLight US Hourly-Ttl AADT": "higher",
    "5th Nearest StreetLight US Hourly-Ttl AADT": "higher",
    "6th Nearest StreetLight US Hourly-Ttl AADT": "higher",
    "Nearest StreetLight US Hourly-ttl_breakfast": "higher",
    "Nearest StreetLight US Hourly-ttl_lunch": "higher",
    "Nearest StreetLight US Hourly-ttl_afternoon": "higher",
    "Nearest StreetLight US Hourly-ttl_dinner": "higher",
    "Nearest StreetLight US Hourly-ttl_night": "higher",
    "Nearest StreetLight US Hourly-ttl_overnight": "higher",
    "nearby_traffic_lights_count": "higher",
    "tunnel_length (in ft.)": "higher",
    "total_weekly_operational_hours": "higher",
    "Count of ChainXY VT - Building Supplies": "higher",
    "Count of ChainXY VT - Department Store": "higher",
    "Count of ChainXY VT - Grocery": "higher",
    "Count of ChainXY VT - Mass Merchant": "higher",
    "Count of ChainXY VT - Real Estate Model": "higher",
    "Sum ChainXY": "higher",
    "count_of_target_5miles": "higher",
    "count_of_costco_5miles": "higher",
    "count_of_walmart_5miles": "higher",
    "count_of_bestbuy_5miles": "higher",
    "competitor_1_google_user_rating_count": "higher",
    # Lower is better
    "total_precipitation_mm": "lower",
    "rainy_days": "lower",
    "total_snowfall_cm": "lower",
    "snowy_days": "lower",
    "days_below_freezing": "lower",
    "avg_daily_max_windspeed_ms": "lower",
    "competitors_count": "lower",
    "competitor_1_distance_miles": "lower",
    "distance_from_nearest_target": "lower",
    "distance_from_nearest_costco": "lower",
    "distance_from_nearest_walmart": "lower",
    "distance_from_nearest_bestbuy": "lower",
    "distance_nearest_traffic_light_1": "lower",
    "distance_nearest_traffic_light_2": "lower",
    "distance_nearest_traffic_light_3": "lower",
    "distance_nearest_traffic_light_4": "lower",
    "distance_nearest_traffic_light_5": "lower",
    "distance_nearest_traffic_light_6": "lower",
    "distance_nearest_traffic_light_7": "lower",
    "distance_nearest_traffic_light_8": "lower",
    "distance_nearest_traffic_light_9": "lower",
    "distance_nearest_traffic_light_10": "lower",
}
