"""
Export peer rows + value ranges from Type_of_carwash_final.xlsx for the
weather quantile benchmark static UI (client-side percentile + avg wash splits).

Source: app/modelling/ds/Type_of_carwash_final.xlsx (482 sites: weather + current_count + carwash).

Output: scoringmetric/approach2/v3/weather_bench_peer_data.js
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
EXCEL = ROOT / "app" / "modelling" / "ds" / "Type_of_carwash_final.xlsx"
OUT_JS = ROOT / "scoringmetric" / "approach2" / "v3" / "weather_bench_peer_data.js"

# API metric_key → (excel column, direction for adjusted percentile, unit label)
WEATHER_METRICS = {
    "dirt-trigger-days": ("weather_rainy_days", "higher", "days/year"),
    "dirt-deposit-severity": ("weather_total_snowfall_cm", "lower", "cm snowfall/year"),
    "comfortable-washing-days": ("weather_days_pleasant_temp", "higher", "days/year"),
    "shutdown-risk-days": ("weather_days_below_freezing", "lower", "days/year"),
}


def main() -> None:
    if not EXCEL.exists():
        raise SystemExit(f"Missing Excel: {EXCEL}")
    df = pd.read_excel(EXCEL, engine="openpyxl")
    n = len(df)
    if "current_count" not in df.columns:
        raise SystemExit("Excel must include current_count")

    ranges: dict = {}
    for key, (col, direction, unit) in WEATHER_METRICS.items():
        s = pd.to_numeric(df[col], errors="coerce").dropna()
        if s.empty:
            continue
        ranges[key] = {
            "column": col,
            "direction": direction,
            "unit": unit,
            "min": float(s.min()),
            "max": float(s.max()),
            "p10": float(s.quantile(0.10)),
            "p25": float(s.quantile(0.25)),
            "p50": float(s.median()),
            "p75": float(s.quantile(0.75)),
            "p90": float(s.quantile(0.90)),
        }

    wash = pd.to_numeric(df["current_count"], errors="coerce")
    peers: list[dict] = []
    for i in range(n):
        row = {
            "wash": float(wash.iloc[i]) if pd.notna(wash.iloc[i]) else None,
            "weather_rainy_days": _f(df, i, "weather_rainy_days"),
            "weather_total_snowfall_cm": _f(df, i, "weather_total_snowfall_cm"),
            "weather_days_pleasant_temp": _f(df, i, "weather_days_pleasant_temp"),
            "weather_days_below_freezing": _f(df, i, "weather_days_below_freezing"),
        }
        if row["wash"] is None:
            continue
        peers.append(row)

    wash_only = pd.to_numeric(df["current_count"], errors="coerce").dropna().astype(float)
    wash_sorted = sorted(wash_only.tolist())

    payload = {
        "source": str(EXCEL.relative_to(ROOT)),
        "n_sites": len(peers),
        "ranges": ranges,
        "peers": peers,
        "peer_wash_sample": wash_sorted[:500] if len(wash_sorted) > 500 else wash_sorted,
    }

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    js = (
        "// Auto-generated by app/modelling/ds/export_weather_bench_frontend.py\n"
        "// Do not edit by hand — re-run: python -m app.modelling.ds.export_weather_bench_frontend\n"
        "window.WEATHER_BENCH_DATA = "
        + json.dumps(payload, indent=0)
        + ";\n"
    )
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"Wrote {OUT_JS} ({len(peers)} peer rows, wash sample {len(payload['peer_wash_sample'])})")


def _f(df: pd.DataFrame, i: int, col: str) -> float | None:
    v = df.iloc[i].get(col)
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


if __name__ == "__main__":
    main()
